---
language: objective-c

os:
  - osx

osx_image: xcode7

install:
    - sudo easy_install pip
    - sudo pip install ansible
    - mkdir -p /tmp/roles
    - "{ echo '[defaults]'; echo 'roles_path = ../:/tmp/roles'; } >> ansible.cfg"
    - ansible-galaxy install -f -r tests/requirements.yml -p /tmp/roles

script:
  - "ansible-playbook -i tests/inventory tests/travis.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/travis.yml --connection=local"
