---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible role to sets up a complete CLI environment on OSX. This role is part of the Superlumic project that aims to simplify repeat computer setups on OSX, 10.10 and up.
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - roderik.superlumic-homebrew
  - roderik.superlumic-osx-defaults

