---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install sublime text 3
  homebrew_cask: name=sublime-text state=present

- name: create directories
  file:
    path: "{{item}}"
    state: directory
    recurse: yes
  with_items:
    - ~/Library/Application Support/Sublime Text 3
    - ~/Library/Application Support/Sublime Text 3/Packages
    - ~/Library/Application Support/Sublime Text 3/Packages/User
    - ~/Library/Application Support/Sublime Text 3/Installed Packages

- name: download package control
  get_url:
    url: "http://sublime.wbond.net/Package%20Control.sublime-package"
    dest: "~/Library/Application Support/Sublime Text 3/Installed Packages/Package Control.sublime-package"

- name: get and update all sublime plugins
  git: update=yes version="{{item.version}}" repo="{{item.repo}}" dest="~/Library/Application Support/Sublime Text 3/Packages/{{item.dest}}"
  with_items: "{{ sublime_packages }}"

- name: render the sublime config file
  template: src=config.j2 dest="~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
