---
- name: install cask applications for all users
  homebrew_cask: name={{item}} state=present
  with_items:
    - slack
    - google-drive
    - keepingyouawake
    - docker
    - firefox
    - iterm2
    - mou
    - sublime-text
    - shiftit

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - elasticsearch
    - git
    - node
    - postgresql
    - redis
    - rhino
    - selenium-server-standalone

# - name: download gvm
#   get_url:
#     url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
#     dest: /tmp/gvm-install.sh
#     mode: 0440
# - name: install gvm
#   command: command -v gvm >/dev/null 2>&1 || /usr/bin/env bash /tmp/gvm-install.sh
#
# - name: setting path
#   sudo: no
#   action: shell source /Users/{{ansible_user_id}}/.gvm/scripts/gvm
