---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible profile role for all users
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - roderik.superlumic-computername
  - roderik.superlumic-cli
