---

- name: tap
  homebrew_tap: tap={{item}} state=present
  with_items:
    - homebrew/versions

- name: install dependencies
  homebrew: name={{item}} state=latest
  with_items:
    - coreutils
    - bash-completion2

- name: download config files
  become: yes
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - { url: 'https://raw.githubusercontent.com/trapd00r/LS_COLORS/master/LS_COLORS', dest: /etc/LS_COLORS}
    - { url: 'https://raw.githubusercontent.com/chriskempson/base16-shell/master/scripts/base16-eighties.sh', dest: /etc/base16-eighties.dark.sh}

- name: place the different configuration files into place
  become: yes
  copy:
    src: "bashrc.{{item}}.sh"
    dest: "/etc/bashrc.{{item}}.sh"
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - prompt
    - coloring
    - cask
    - completion
    - editor
    - history
    - docker
    - aliases

- name: add the different configuration files to bashrc
  become: yes
  lineinfile: >
    dest=/etc/bashrc
    regexp="bashrc.{{item}}.sh"
    line="if [ -f /etc/bashrc.{{item}}.sh ]; then . /etc/bashrc.{{item}}.sh; fi"
    state=present
    create=true
  with_items:
    - prompt
    - coloring
    - cask
    - completion
    - editor
    - history
    - docker
    - aliases
