---
galaxy_info:
  author: Roderik van der Veer
  description: Ansible profile role for developers
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Darwin
      versions:
        - all
  categories:
    - system
dependencies:
  - roderik.superlumic-computername
  - roderik.superlumic-cli
  - roderik.superlumic-homebrew
  - roderik.superlumic-mysql
  - roderik.superlumic-php
  - roderik.superlumic-sublimetext
  - roderik.superlumic-skylab
  - roderik.superlumic-node
  - roderik.superlumic-vim
  - profile-all
